"""empty message

Revision ID: f7df24f46daa
Revises: 
Create Date: 2022-10-01 18:55:15.661993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7df24f46daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('user')
    op.drop_constraint('address_user_id_fkey', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'site_user', ['user_id'], ['id'])
    op.drop_constraint('ledger_line_item_created_by_fkey', 'ledger_line_item', type_='foreignkey')
    op.create_foreign_key(None, 'ledger_line_item', 'site_user', ['created_by'], ['id'])
    op.add_column('mail_in_repair', sa.Column('repair_date_received', sa.DateTime(), nullable=True))
    op.add_column('mail_in_repair', sa.Column('repair_date_completed', sa.DateTime(), nullable=True))
    op.drop_constraint('mail_in_repair_repair_user_id_fkey', 'mail_in_repair', type_='foreignkey')
    op.create_foreign_key(None, 'mail_in_repair', 'site_user', ['repair_user_id'], ['id'])
    op.drop_constraint('mail_in_web_web_service_user_id_fkey', 'mail_in_web', type_='foreignkey')
    op.create_foreign_key(None, 'mail_in_web', 'site_user', ['web_service_user_id'], ['id'])
    op.drop_constraint('point_created_by_fkey', 'point', type_='foreignkey')
    op.create_foreign_key(None, 'point', 'site_user', ['created_by'], ['id'])
    op.drop_constraint('todo_user_id_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'site_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('todo_user_id_fkey', 'todo', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'point', type_='foreignkey')
    op.create_foreign_key('point_created_by_fkey', 'point', 'user', ['created_by'], ['id'])
    op.drop_constraint(None, 'mail_in_web', type_='foreignkey')
    op.create_foreign_key('mail_in_web_web_service_user_id_fkey', 'mail_in_web', 'user', ['web_service_user_id'], ['id'])
    op.drop_constraint(None, 'mail_in_repair', type_='foreignkey')
    op.create_foreign_key('mail_in_repair_repair_user_id_fkey', 'mail_in_repair', 'user', ['repair_user_id'], ['id'])
    op.drop_column('mail_in_repair', 'repair_date_completed')
    op.drop_column('mail_in_repair', 'repair_date_received')
    op.drop_constraint(None, 'ledger_line_item', type_='foreignkey')
    op.create_foreign_key('ledger_line_item_created_by_fkey', 'ledger_line_item', 'user', ['created_by'], ['id'])
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_user_id_fkey', 'address', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=127), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=127), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=127), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('public_id', name='user_public_id_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
