"""empty message

Revision ID: ab90a4031bfa
Revises: 1e43fe918b16
Create Date: 2023-01-25 16:29:02.393433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab90a4031bfa'
down_revision = '1e43fe918b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('line_one', sa.String(length=127), nullable=True))
    op.add_column('address', sa.Column('line_two', sa.String(length=127), nullable=True))
    op.add_column('address', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('address', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('address', sa.Column('postal_code', sa.String(length=50), nullable=True))
    op.add_column('address', sa.Column('country', sa.String(length=80), nullable=True))
    op.drop_column('address', 'address_phone')
    op.drop_column('address', 'address_city')
    op.drop_column('address', 'address_country')
    op.drop_column('address', 'first_name')
    op.drop_column('address', 'address_postal_code')
    op.drop_column('address', 'address_state')
    op.drop_column('address', 'last_name')
    op.drop_column('address', 'address_line_two')
    op.drop_column('address', 'address_email')
    op.drop_column('address', 'address_line_one')
    op.add_column('site_user', sa.Column('phone', sa.String(length=127), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_user', 'phone')
    op.add_column('address', sa.Column('address_line_one', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_line_two', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('last_name', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_postal_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('first_name', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_country', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_city', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_phone', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.drop_column('address', 'country')
    op.drop_column('address', 'postal_code')
    op.drop_column('address', 'state')
    op.drop_column('address', 'city')
    op.drop_column('address', 'line_two')
    op.drop_column('address', 'line_one')
    # ### end Alembic commands ###
