"""empty message

Revision ID: bcaeacc15786
Revises: 84c62c8bb1bc
Create Date: 2023-03-16 16:01:29.505883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcaeacc15786'
down_revision = '84c62c8bb1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_work_order_id_fkey', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'order', ['work_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key('device_work_order_id_fkey', 'device', 'work_order', ['work_order_id'], ['id'])
    # ### end Alembic commands ###
